<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Create new account</name>
   <tag></tag>
   <elementGuidId>4e1c2f85-5d00-4d27-bc54-1320adc08a37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '#' and @id = 'u_0_0_5C' and (text() = 'Create new account' or . = 'Create new account')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Create new account')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#u_0_0_5C</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6b233a04-a382-45db-beec-496bdc2cc551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5a9d8735-ceca-4cab-9226-b233108eb398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_42ft _4jy0 _6lti _4jy6 _4jy2 selected _51sy</value>
      <webElementGuid>6a0346e2-21ea-4f0c-820a-c15352b5ffd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>d746eddf-8426-4b64-8fab-6ed2fbddddf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ajaxify</name>
      <type>Main</type>
      <value>/reg/spotlight/</value>
      <webElementGuid>d2d37423-626b-419b-b96a-34cd04235a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u_0_0_5C</value>
      <webElementGuid>7ab74b91-7aff-4b97-9e20-c14d6d0a1491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>open-registration-form-button</value>
      <webElementGuid>3b91a13e-6717-49c3-ba82-9e89346592be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>b003bed8-893d-48f1-ac43-bfad0890da99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create new account</value>
      <webElementGuid>62e91f0b-d14d-4052-a870-b9721e972576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_0_0_5C&quot;)</value>
      <webElementGuid>f9ae43cf-7c51-481f-a469-87624a7ef59a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='u_0_0_5C']</value>
      <webElementGuid>e94d040d-d875-4cfb-b041-b1d1732b36ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='u_0_2_0E']/div[5]/a</value>
      <webElementGuid>3a92bbe7-c782-4d4b-b444-f6bfd873db5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Create new account')]</value>
      <webElementGuid>30055480-fb72-41b3-bf67-283130e8b404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>fea4d459-168a-473d-834d-e2361d5da901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a</value>
      <webElementGuid>36d3da62-db75-4924-9938-4244707eb4f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'u_0_0_5C' and (text() = 'Create new account' or . = 'Create new account')]</value>
      <webElementGuid>aec7c189-fe85-4968-803b-10abba1d4e12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
